#!/usr/bin/env python3
"""Generate the hybrid finetuning job grid (mirrors the deep-only ablation grid).

For each dataset x encoder x method, emits one full-finetune job (no freeze
variant -- the encoder is always unfrozen), loading that dataset's per-dataset
SSL checkpoint at native channels/window length:
  - <combo>_self : per-dataset SSL checkpoint, native channels/window length

Writes one line per job to the path in the OUT_JOBS env var (default:
runs/hybrid/_jobs.txt), atomically (write to a temp file + os.replace) so a
concurrent reader (configs/hybrid_queue_runner.sh) never observes a
truncated/partial file:
    <run_name> <hc_framework.main CLI args...>

The full grid (all encoders/methods/datasets) is generated by this script -- it is
generic. configs/run_hybrid_all.sh restricts it via ENCODERS/METHODS env vars
(default: patchtst + cnn_tfc, simclr + mae).

IMPORTANT: every invocation writes to the *same* OUT_JOBS path by default. If
you need to run two grids concurrently (e.g. VARIANTS=frozen and VARIANTS=lora
at the same time), set OUT_JOBS to a distinct path for each -- otherwise the
second invocation's write can race with a queue_runner.sh still reading the
first file (even with atomic replace, a reader mid-loop would silently miss
the remaining lines of the file it started reading).
"""
from __future__ import annotations

import os
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

ALL_DATASETS = ["actbecalf", "uci_har", "pamap2", "wisdm", "vehkaoja", "marinara", "horse"]

NATIVE_T = {
    "actbecalf": 75, "uci_har": 128,
    "vehkaoja": 300, "marinara": 300, "pamap2": 300, "wisdm": 60,
    "horse": 200,
}

# Methods that have an MAE pretraining variant in the ablation grid.
MAE_OK = {"patchtst", "patchtsmixer"}


def best_patch_length(T: int, requested: int = 8) -> int:
    """Mirror encoders.patchtst._best_patch_length: the largest
    divisor of T that is <= requested. The 'self' checkpoint's patch embedding was
    pretrained with this patch_length, so the hybrid encoder must use the same value
    for the positional/patch-embedding weights to line up."""
    pl = min(requested, T)
    while pl > 1 and T % pl != 0:
        pl -= 1
    return pl


def patchtst_args(context_length: int, patch_len: int) -> list[str]:
    return [
        "--context_length", str(context_length),
        "--patch_len", str(patch_len),
        "--stride", str(patch_len),
        "--d_model", "128", "--n_heads", "4", "--n_layers", "3",
    ]


def self_ckpt(dataset: str, encoder: str, method: str) -> Path:
    return REPO / "runs" / dataset / f"{method}_{encoder}_freeze" / "artifacts" / "checkpoints" / "pretrain_best.pt"


def main() -> None:
    encoders = os.environ.get("ENCODERS", "patchtst cnn_tfc").split()
    methods = os.environ.get("METHODS", "simclr mae").split()
    datasets = os.environ.get("DATASETS", "").split() or ALL_DATASETS
    variants = os.environ.get("VARIANTS", "full frozen").split()

    jobs: list[str] = []
    for dataset in datasets:
        if dataset not in NATIVE_T:
            continue
        T = NATIVE_T[dataset]

        for encoder in encoders:
            for method in methods:
                if method == "mae" and encoder not in MAE_OK:
                    continue

                flags_common = ["--model", encoder, "--input_mode", "hybrid",
                                "--from_pt", dataset, "--mode", "supervised"]

                # Per-dataset SSL checkpoint, native channels/window length.
                sckpt = self_ckpt(dataset, encoder, method)
                if not sckpt.exists():
                    continue

                extra = ["--channel_policy", "all", "--resample_t", "0",
                         "--init_encoder_from", str(sckpt)]
                if encoder == "patchtst":
                    extra += patchtst_args(T, best_patch_length(T))

                if "lora" in variants:
                    if encoder == "patchtst":
                        run_name = f"{dataset}/{method}_{encoder}_lora_self"
                        jobs.append(" ".join([run_name] + flags_common + extra + ["--lora"]))
                    continue

                if "full" in variants:
                    # Legacy 3-part name reused so the 21 already-completed
                    # runs stay cached and are not recomputed.
                    run_name = f"{dataset}/{method}_{encoder}_self"
                    jobs.append(" ".join([run_name] + flags_common + extra))

                if "frozen" in variants:
                    run_name = f"{dataset}/{method}_{encoder}_frozen_self"
                    jobs.append(" ".join([run_name] + flags_common + extra + ["--freeze_encoder"]))

    out = Path(os.environ.get("OUT_JOBS", str(REPO / "runs" / "hybrid" / "_jobs.txt")))
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_suffix(out.suffix + f".tmp{os.getpid()}")
    tmp.write_text("\n".join(jobs) + ("\n" if jobs else ""))
    os.replace(tmp, out)  # atomic rename: a concurrent reader of `out` never sees a partial write
    print(f"wrote {len(jobs)} jobs -> {out}")


if __name__ == "__main__":
    main()
